import { Component, OnInit } from '@angular/core';
import {ActivatedRoute} from '@angular/router';
@Component({
  selector: 'app-info',
  templateUrl: './info.component.html',
  styleUrls: ['./info.component.css']
})
export class InfoComponent implements OnInit {

  araclar = [
    {id:1,img: "assets/img/m1.jpg",baslik:'2014 HARLEY DAVIDSON / CVO ULTRA LIMITED',fiyat:'162.500 TL' ,markatext:'MARKA', marka: ':HARLEY DAVIDSON',modeltext:'MODEL',model: ':CVO ULTRA LIMITED',modelyilitext:'MODEL YILI',modelyili:':2014',kmtext:'KİLOMETRE',km:':18.973 KM',motorhacmitext:'MOTOR HACMİ',motorhacmi:':1801',motorgucutext:'MOTOR GÜCÜ',motorgucu:':97',yakittext:'YAKIT',yakit:':BENZİN',vitestext:'VİTES',vites:':OTOMATİK',govdetext:'GÖVDE TİPİ',govdetip:':MOTOSİKLETLER',disrenktext:'DIŞ RENK',disrenk:':MAVİ',icrenktext:'İÇ RENK',icrenk:':SİYAH',dosemetext:'DÖŞEME',doseme:':DERİ',kaplamatext:'KAPLAMA',kaplama:':ALUMINYUM',konumtext:'KONUM',konum:'YENİKÖY SHOWROOM',ithalatdurum:'BAYİ ÇIKIŞLI',bolge:'YENİKÖY SHOWROOM',tel:'+90 212 223 44 44 (PBX)',adres:'Köybaşı Cd. No:94 Yeniköy / İstanbul'},
    {id:2,img: "assets/img/m2.jpg",baslik:'2015 HARLEY DAVIDSON / VRSCDX NIGHT ROD SPECIAL',fiyat:'242.000 TL' ,markatext:'MARKA', marka: ':HARLEY DAVIDSON',modeltext:'MODEL',model: ':VRSCDX NIGHT ROD SPECIAL',modelyilitext:'MODEL YILI',modelyili:':2015',kmtext:'KİLOMETRE',km:':1.000 KM',motorhacmitext:'MOTOR HACMİ',motorhacmi:':1247',motorgucutext:'MOTOR GÜCÜ',motorgucu:':122',yakittext:'YAKIT',yakit:':BENZİN',vitestext:'VİTES',vites:':MANUAL',govdetext:'GÖVDE TİPİ',govdetip:':MOTOSİKLETLER',disrenktext:'DIŞ RENK',disrenk:':SİYAH',icrenktext:'İÇ RENK',icrenk:':SİYAH',dosemetext:'DÖŞEME',doseme:':DERİ',konumtext:'KONUM',konum:'YENİKÖY SHOWROOM',ithalatdurum:'BAYİ ÇIKIŞLI',bolge:'YENİKÖY SHOWROOM',tel:'+90 212 223 44 44 (PBX)',adres:'Köybaşı Cd. No:94 Yeniköy / İstanbul'},
    {id:3,img: "assets/img/k1.jpg",baslik:'1928 FORD / A SPECIAL ROADSTER',fiyat:'1.400.000 TL' ,markatext:'MARKA', marka: ':FORD',modeltext:'MODEL',model: ':A SPECIAL',modelyilitext:'MODEL YILI',modelyili:':1928',kmtext:'KİLOMETRE',km:':0 KM',motorhacmitext:'MOTOR HACMİ',motorhacmi:':2043',motorgucutext:'MOTOR GÜCÜ',motorgucu:':28',yakittext:'YAKIT',yakit:':BENZİN',vitestext:'VİTES',vites:':MANUAL',govdetext:'GÖVDE TİPİ',govdetip:':KLASİK ARAÇLAR',disrenktext:'DIŞ RENK',disrenk:':YEŞİL',konumtext:'KONUM',konum:'YENİKÖY SHOWROOM',ithalatdurum:'ÖZEL İTHALAT ',bolge:'YENİKÖY SHOWROOM',tel:'+90 212 223 44 44 (PBX)',adres:'Köybaşı Cd. No:94 Yeniköy / İstanbul'},
    {id:4,img: "assets/img/k2.jpg",baslik:'1955 CHEVROLET / BELAIR CONVERTİBLE',fiyat:'245.000 TL' ,markatext:'MARKA', marka: ':CHEVROLET',modeltext:'MODEL',model: ':BELAIR',modelyilitext:'MODEL YILI',modelyili:':1955',kmtext:'KİLOMETRE',km:':50.000 KM',motorhacmitext:'MOTOR HACMİ',motorhacmi:':5700',motorgucutext:'MOTOR GÜCÜ',motorgucu:':220',yakittext:'YAKIT',yakit:':BENZİN',vitestext:'VİTES',vites:':OTOMATİK',govdetext:'GÖVDE TİPİ',govdetip:':KLASİK ARAÇLAR',disrenktext:'DIŞ RENK',disrenk:':MAVİ',icrenktext:'İÇ RENK',icrenk:':MAVİ/BEYAZ',dosemetext:'DÖŞEME',doseme:':DERİ',kaplamatext:'KAPLAMA',kaplama:':ALUMINYUM',konumtext:'KONUM',konum:'İZMİR SHOWROOM',ithalatdurum:'ÖZEL İTHALAT',bolge:'İZMİR SHOWROOM',tel:'+90 232 502 13 10',adres:'Folkart Towers A Blok No: 37 Bayraklı / İzmir'},
    {id:5,img: "assets/img/s1.jpg",baslik:'2018 ASTON MARTIN / Vantage 4.0 V8',fiyat:'2.350.000 TL' ,markatext:'MARKA', marka: ':ASTON MARTIN',modeltext:'MODEL',model: ':Vantage',modelyilitext:'MODEL YILI',modelyili:':2018',kmtext:'KİLOMETRE',km:':3.000 KM',motorhacmitext:'MOTOR HACMİ',motorhacmi:':3982',motorgucutext:'MOTOR GÜCÜ',motorgucu:':510',yakittext:'YAKIT',yakit:':BENZİN',vitestext:'VİTES',vites:':F-1/OTOMATİK',govdetext:'GÖVDE TİPİ',govdetip:':SPOR ARAÇLAR',disrenktext:'DIŞ RENK',disrenk:':LIME ESSENCE',icrenktext:'İÇ RENK',icrenk:':ALL PURE BLACK LEATHER',dosemetext:'DÖŞEME',doseme:':DERİ',kaplamatext:'KAPLAMA',kaplama:':PIANO BLACK/ALUMINYUM',konumtext:'KONUM',konum:'İZMİR SHOWROOM',ithalatdurum:'BAYİ ÇIKIŞLI ',bolge:'İZMİR SHOWROOM',tel:'+90 232 502 13 10',adres:'Folkart Towers A Blok No: 37 Bayraklı / İzmir'},
    {id:6,img: "assets/img/s2.jpg",baslik:'2015 BMW / İ Serisi İ8 PURE eDRIVE',fiyat:'590.000 TL' ,markatext:'MARKA', marka: ':BMW',modeltext:'MODEL',model: ':İ Serisi',modelyilitext:'MODEL YILI',modelyili:':2015',kmtext:'KİLOMETRE',km:':61.107 KM',motorhacmitext:'MOTOR HACMİ',motorhacmi:':1500',motorgucutext:'MOTOR GÜCÜ',motorgucu:':362',yakittext:'YAKIT',yakit:':BENZİN/ELEKTRİK',vitestext:'VİTES',vites:':F-1/OTOMATİK',govdetext:'GÖVDE TİPİ',govdetip:':SPOR ARAÇLAR',disrenktext:'DIŞ RENK',disrenk:':SİYAH/BEYAZ ',icrenktext:'İÇ RENK',icrenk:':KAHVERENGİ ',dosemetext:'DÖŞEME',doseme:':DERİ',kaplamatext:'KAPLAMA',kaplama:':PIANO BLACK/ALUMINYUM',konumtext:'KONUM',konum:'İZMİR SHOWROOM',ithalatdurum:'BAYİ ÇIKIŞLI ',bolge:'İZMİR SHOWROOM',tel:'+90 232 502 13 10',adres:'Folkart Towers A Blok No: 37 Bayraklı / İzmir'},
    {id:7,img: "assets/img/arazi1.jpg",baslik:'2019 AUDI / Q8 50 TDI QUATTRO',fiyat:'1.550.000 TL' ,markatext:'MARKA', marka: ':AUDI',modeltext:'MODEL',model: ':Q8',modelyilitext:'MODEL YILI',modelyili:':2019',kmtext:'KİLOMETRE',km:':0 KM',motorhacmitext:'MOTOR HACMİ',motorhacmi:':2967',motorgucutext:'MOTOR GÜCÜ',motorgucu:':286',yakittext:'YAKIT',yakit:':DİZEL',vitestext:'VİTES',vites:':OTOMATİK',govdetext:'GÖVDE TİPİ',govdetip:':ARAZİ ARAÇLARI',disrenktext:'DIŞ RENK',disrenk:':SİYAH ',icrenktext:'İÇ RENK',icrenk:':TABA ',dosemetext:'DÖŞEME',doseme:':DERİ',kaplamatext:'KAPLAMA',kaplama:':ALUMINYUM',konumtext:'KONUM',konum:'YENİKÖY SHOWROOM',ithalatdurum:'YENİKÖY MOTORS ',bolge:'YENİKÖY SHOWROOM',tel:'+90 212 223 44 44 (PBX)',adres:'Köybaşı Cd. No:94 Yeniköy / İstanbul'},
    {id:8,img: "assets/img/arazi2.jpg",baslik:'2019 LAMBORGHINI / URUS 4.0 V8',fiyat:'4.975.000 TL' ,markatext:'MARKA', marka: ':LAMBORGHINI',modeltext:'MODEL',model: ':URUS',modelyilitext:'MODEL YILI',modelyili:':2019',kmtext:'KİLOMETRE',km:':0 KM',motorhacmitext:'MOTOR HACMİ',motorhacmi:':3996',motorgucutext:'MOTOR GÜCÜ',motorgucu:':650',yakittext:'YAKIT',yakit:':BENZİN',vitestext:'VİTES',vites:':OTOMATİK',govdetext:'GÖVDE TİPİ',govdetip:':ARAZİ ARAÇLARI',disrenktext:'DIŞ RENK',disrenk:':NERO AADE ',icrenktext:'İÇ RENK',icrenk:':TERRA ASIA VINTAGE ',dosemetext:'DÖŞEME',doseme:':DERİ',kaplamatext:'KAPLAMA',kaplama:':ALUMINYUM',konumtext:'KONUM',konum:'YENİKÖY SHOWROOM',ithalatdurum:'BAYİ ÇIKIŞLI ',bolge:'YENİKÖY SHOWROOM',tel:'+90 212 223 44 44 (PBX)',adres:'Köybaşı Cd. No:94 Yeniköy / İstanbul'},
    {id:9,img: "assets/img/binek1.jpg",baslik:'2018 FORD / Focus FORD FOCUS 1.5 TDCİ STYLE',fiyat:'115.500 TL' ,markatext:'MARKA', marka: ':FORD',modeltext:'MODEL',model: ':Focus',modelyilitext:'MODEL YILI',modelyili:':2018',kmtext:'KİLOMETRE',km:':45.900 KM',motorhacmitext:'MOTOR HACMİ',motorhacmi:':1499',motorgucutext:'MOTOR GÜCÜ',motorgucu:':120',yakittext:'YAKIT',yakit:':DİZEL',vitestext:'VİTES',vites:':MANUAL',govdetext:'GÖVDE TİPİ',govdetip:':BİNEK ARAÇLAR',disrenktext:'DIŞ RENK',disrenk:':GRİ  ',icrenktext:'İÇ RENK',icrenk:':SİYAH ',dosemetext:'DÖŞEME',doseme:':KUMAŞ',kaplamatext:'KAPLAMA',kaplama:':PIANO BLACK',konumtext:'KONUM',konum:'KARTAL SHOWROOM',ithalatdurum:'BAYİ ÇIKIŞLI ',bolge:'KARTAL SHOWROOM',tel:'+90 216 344 00 12',adres:'Hukukçular Towers Cevizli Mh. Mustafa Kemal Cd. No: 66. D 2/3 blok, Kartal / İstanbul'},
    {id:10,img: "assets/img/binek2.jpg",baslik:'2019 MERCEDES / CLA 180 - AMG',fiyat:'495.000 TL' ,markatext:'MARKA', marka: ':MERCEDES',modeltext:'MODEL',model: ':CLA',modelyilitext:'MODEL YILI',modelyili:':2019',kmtext:'KİLOMETRE',km:':0 KM',motorhacmitext:'MOTOR HACMİ',motorhacmi:':1332',motorgucutext:'MOTOR GÜCÜ',motorgucu:':136',yakittext:'YAKIT',yakit:':BENZİN',vitestext:'VİTES',vites:':OTOMATİK',govdetext:'GÖVDE TİPİ',govdetip:':BİNEK ARAÇLAR',disrenktext:'DIŞ RENK',disrenk:':BEYAZ ',icrenktext:'İÇ RENK',icrenk:':SİYAH ',dosemetext:'DÖŞEME',doseme:':DERİ/ALCANTARA',kaplamatext:'KAPLAMA',kaplama:':ALUMINYUM',konumtext:'KONUM',konum:'YENİKÖY SHOWROOM',ithalatdurum:'YENİKÖY MOTORS ',bolge:'YENİKÖY SHOWROOM',tel:'+90 212 223 44 44 (PBX)',adres:'Köybaşı Cd. No:94 Yeniköy / İstanbul'},

   
];


  constructor(private route:ActivatedRoute) { }



  public motoId;
  ngOnInit() {
    let id=parseInt(this.route.snapshot.paramMap.get('id'));
    this.motoId=id;
  }

}
